### PR TITLE
Added parameter to hide documentation in the swagger UI

### PR DESCRIPTION
**Pull request by 0x78f1935**
Came across the following issue: https://github.com/marshmallow-code/flask-smorest/issues/110
Decided to make a PR for it.

### CODE REVIEW

**Comment by lafrech** [comment]
Hi. Thanks for contributing.

Not sure about the name of the parameter. `document` sounds too generic. I don't find `render` very expressive. `hide_from_doc` would be expressive. I'm open to suggestions.

Regarding the implementation, propagate the parameter to `add_url_route` and make things happen there.

**Comment by 0x78f1935** [comment]
Sorry I was sleeping or something, latest version should work 👍

**Comment by 0x78f1935** [comment]
Any news on this? @lafrech

**Review by lafrech — CHANGES_REQUESTED** [review]
I can't find great a parameter name. I think `hidden_from_api_spec` would be better. I shall make this consistent across the lib, but the JSON that is produced is more a specification than a documentation (if I understand [this](https://swagger.io/resources/articles/difference-between-api-documentation-specification/) correctly).

Add unit tests, squash the commits and you're done.

Also, please add your name to AUTHORS file (can be in a separate commit).

**Pull request closed without merging**
