### PR TITLE
feat(Converters): Improve support of AnyConverter to list values

### PR DESCRIPTION
**Pull request by deytao**
Currently it is not possible to list values used in the `AnyConverter`.
It will help to have this functionality to ensure that the correct values are documented.

### CODE REVIEW

**Comment by deytao** [comment]
Any thoughts?

**Comment by lafrech** [comment]
Looks like we need to change the whole behaviour, here.

Current approach associates a converter with a (type, format) couple. We need to generalize this to use a callable, I guess, to generate the docs from the converter object.

This will allow to support other converters parameters:

https://werkzeug.palletsprojects.com/en/1.0.x/routing/#built-in-converters

This need was identified in #65 but I never took the time to dig into it.

**Comment by deytao** [comment]
Thanks for your answer, I find a way to do the same by using the `location="path"` and the validator `AnyOf`.
It's not perfect but it does the job in the mean time.
I guess I can close this PR if you'll address it later.

**Comment by lafrech** [comment]
All right. I started working on it but I'm not done yet.

**Pull request closed without merging**
