### PR TITLE
Support multiple APIs in a single app

### PR DESCRIPTION
**Pull request by lafrech**
Rebase / rework of @petraszd's #422.

### CODE REVIEW

**Comment by lafrech** [comment]
I'm still not convinced there couldn't be name clashes in `_find_current_api` if someone created a blueprint with a name containing a dot that would match a nested blueprint name. Admittedly, this is a bit unlikely, but...

**Review by petraszd — APPROVED** [review]

**Comment by petraszd** [comment]
@lafrech 

It is impossible to create a blueprint with a dot `.` in it's name:
https://github.com/pallets/flask/blob/2.0.x/src/flask/blueprints.py#L198-L199

**Comment by lafrech** [comment]
Oh, good. I thought I had tested this. I guess I hadn't.

Thanks for reviewing.

**Comment by lafrech** [comment]
I just performed a last review and a few minor edits. This is good to go.

Before merging, I'd like to tests against my code base at work next week, just in case, although I'm sure it's all non-breaking.

I'll hopefully release after that.

**Comment by lafrech** [comment]
It is worth noting that the `Api` instance is now accessible at the following path:

```py
app.extensions["flask-smorest"]["apis"][""]["ext_obj"]
```

Users accessing the `Api` object at `app.extensions["flask-smorest"]["ext_obj"]` will have to adapt their code.

We could add a deprecated shortcut there, but frankly I don't think it is worth it.

**Pull request merged**
