### PR TITLE
Fix basePath if app is deployed on a path (openAPI v3)

### PR DESCRIPTION
**Pull request by revmischa**
#55 

Same fix as flask_apispec https://github.com/jmcarp/flask-apispec/pull/125/files

### CODE REVIEW

**Comment by revmischa** [comment]
Hm actually this only fixes openapi 2.  Need to find out how to define servers for v3.

**Comment by lafrech** [comment]
Closing for now. Let's discuss this in https://github.com/Nobatek/flask-rest-api/issues/55.

**Comment by revmischa** [comment]
Would like to look at this again
Documentation for `servers`: https://swagger.io/docs/specification/api-host-and-base-path/
Rationale is in #55

**Comment by revmischa** [comment]
I am using this modification and it fixes swagger on Lambda for me. Can we re-open it?

**Pull request closed without merging**
